# Generated by Django 6.0.5 on 2026-05-27 07:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(primary_key=True, serialize=False, verbose_name=20)),
                ('article_title', models.CharField(default='Шаблон заголовка', verbose_name=20)),
                ('article_annotation', models.CharField(default='Loren ipsum', verbose_name=200)),
                ('article_preview_image', models.BinaryField(default=b'')),
                ('article_text', models.TextField(default='Loren ipsum')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2026, 5, 27, 10, 58, 53, 743377))),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Article_Picture',
            fields=[
                ('picture_id', models.CharField(primary_key=True, serialize=False, verbose_name=20)),
                ('picture', models.BinaryField(default=b'')),
                ('article_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kernel_app.article')),
            ],
            options={
                'verbose_name': 'Article_Picture',
                'verbose_name_plural': 'Article_Pictures',
            },
        ),
    ]
