# Generated by Django 6.0.5 on 2026-05-28 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 28, 14, 57, 57, 281637)),
        ),
    ]
